In [15]:
print("hello Jupyter")

hello Jupyter


1 Dim Array

In [72]:
import numpy as np
arr = np.array(['10',"20",30])
print(arr)
print(type(arr))     #datatype of variable
print(len(arr))      #number of nested values
print(np.shape(arr)) #rows, columns
print(np.size(arr))  #number of elements
print(np.ndim(arr))  #number of dimentions of array
print(arr.dtype)     #datatype of array

['10' '20' '30']
<class 'numpy.ndarray'>
3
(3,)
3
1
<U11


2 Dim Array

In [68]:
d2arr = np.array([[10.5,30,50,70,90],[00,20,40,60,80]])
print(d2arr)
print(type(d2arr))     #datatype of variable
print(len(d2arr))      #number of nested values
print(np.shape(d2arr)) #rows, columns
print(np.size(d2arr))  #number of elements
print(np.ndim(d2arr))  #number of dimentions of array
print(d2arr.dtype)     #datatype of array

[[10.5 30.  50.  70.  90. ]
 [ 0.  20.  40.  60.  80. ]]
<class 'numpy.ndarray'>
2
(2, 5)
10
2
float64


In [71]:
d3arr = np.array([[12,34,56,32,57],[45,67,26,76,24],[86,85,57,95,26]])
print(d3arr)
print(type(d3arr))     #datatype of variable
print(len(d3arr))      #number of nested values
print(np.shape(d3arr)) #rows, columns
print(np.size(d3arr))  #number of elements
print(np.ndim(d3arr))  #number of dimentions of array
print(d3arr.dtype)     #datatype of array

[[12 34 56 32 57]
 [45 67 26 76 24]
 [86 85 57 95 26]]
<class 'numpy.ndarray'>
3
(3, 5)
15
2
int32


Slicing

In [17]:
print(arr[0:2])

[10 20]


In [19]:
print(arr[1:3])

[20 30]


In [30]:
print(d2arr[0,:])

[10 30 50 70 90]


In [31]:
print(d2arr[1,:])

[ 0 20 40 60 80]


In [32]:
print(d2arr[0,2:4])

[50 70]


In [39]:
print(d2arr[0:4,0:4])

[[10 30 50 70]
 [ 0 20 40 60]]


In [44]:
print(d2arr[1, 2:4])

[40 60]


In [56]:
print(d3arr[2, 2:4])

[57 95]


Type Cast

In [77]:
print(arr.dtype)           #initial datatype
print(arr.astype(str))     #after typecast
print(d2arr.dtype)         #initial datatype
print(d2arr.astype(int))   #after typecast
print(d3arr.dtype)         #initial datatype
print(d3arr.astype(float)) #after typecast

<U11
['10' '20' '30']
float64
[[10 30 50 70 90]
 [ 0 20 40 60 80]]
int32
[[12. 34. 56. 32. 57.]
 [45. 67. 26. 76. 24.]
 [86. 85. 57. 95. 26.]]


Matematical Operations & Functions

In [83]:
arr1 = np.array([56,12,75,98,45,57,24,84,75,44])
arr2 = np.array([21,43,12,89,54,45,56,56,67,22])
arr3 = np.array([[56,12,75,98,45],[57,24,84,75,44]])
arr4 = np.array([[21,43,12,89,54],[45,56,56,67,22]])

In [88]:
# ADDITION
print(arr1 + arr2)
print(np.add(arr1,arr2))
print()
print(arr3 + arr4)
print()
print(np.add(arr3,arr4))

[ 77  55  87 187  99 102  80 140 142  66]
[ 77  55  87 187  99 102  80 140 142  66]

[[ 77  55  87 187  99]
 [102  80 140 142  66]]

[[ 77  55  87 187  99]
 [102  80 140 142  66]]


In [90]:
# SUBTRACTION
print(arr1 - arr2)
print(np.subtract(arr1,arr2))
print()
print(arr3 - arr4)
print()
print(np.subtract(arr3,arr4))

[ 35 -31  63   9  -9  12 -32  28   8  22]
[ 35 -31  63   9  -9  12 -32  28   8  22]

[[ 35 -31  63   9  -9]
 [ 12 -32  28   8  22]]

[[ 35 -31  63   9  -9]
 [ 12 -32  28   8  22]]


In [92]:
# MULTIPLICATION
print(arr1 * arr2)
print(np.multiply(arr1,arr2))
print()
print(arr3 * arr4)
print()
print(np.multiply(arr3,arr4))

[1176  516  900 8722 2430 2565 1344 4704 5025  968]
[1176  516  900 8722 2430 2565 1344 4704 5025  968]

[[1176  516  900 8722 2430]
 [2565 1344 4704 5025  968]]

[[1176  516  900 8722 2430]
 [2565 1344 4704 5025  968]]


In [94]:
# DIVISION
print(arr1 / arr2)
print(np.divide(arr1,arr2))
print()
print(arr3 / arr4)
print()
print(np.divide(arr3,arr4))

[2.66666667 0.27906977 6.25       1.1011236  0.83333333 1.26666667
 0.42857143 1.5        1.11940299 2.        ]
[2.66666667 0.27906977 6.25       1.1011236  0.83333333 1.26666667
 0.42857143 1.5        1.11940299 2.        ]

[[2.66666667 0.27906977 6.25       1.1011236  0.83333333]
 [1.26666667 0.42857143 1.5        1.11940299 2.        ]]

[[2.66666667 0.27906977 6.25       1.1011236  0.83333333]
 [1.26666667 0.42857143 1.5        1.11940299 2.        ]]


In [101]:
# POWER 
pow = np.array([3])
print(np.power(arr1,pow),'\n')
print(np.power(arr3,pow))

[175616   1728 421875 941192  91125 185193  13824 592704 421875  85184] 

[[175616   1728 421875 941192  91125]
 [185193  13824 592704 421875  85184]]


In [106]:
#SQUAREROOT
squares = np.array([16,9,4,2])
print(np.sqrt(squares))
print(np.sqrt(squares).astype(int))

[4.         3.         2.         1.41421356]
[4 3 2 1]


CONCATENATING ARRAY ELEMENTS

In [129]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]
print(a+b)
c = np.array([10,20,30,40,50])
d = np.array([60,70,80,90,100])
print(np.concatenate([c,d]))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 10  20  30  40  50  60  70  80  90 100]


In [116]:
dim2arr1 = np.array([[32,54],[20,40]])
dim2arr2 = np.array([[94,73],[53,16]])

In [126]:
# CONCATENATE HORIZONTALLY
print(np.hstack([dim2arr1,dim2arr2]),"\n")
print(np.concatenate([dim2arr1,dim2arr2],axis=1))

[[32 54 94 73]
 [20 40 53 16]] 

[[32 54 94 73]
 [20 40 53 16]]


In [128]:
# CONCATENATE VERTICALLY
print(np.vstack([dim2arr1,dim2arr2]),"\n")
print(np.concatenate([dim2arr1,dim2arr2],axis=0))

[[32 54]
 [20 40]
 [94 73]
 [53 16]] 

[[32 54]
 [20 40]
 [94 73]
 [53 16]]


SPLITTING ARRAY ELEMENTS

In [139]:
print(np.array_split(c,1))
print(np.array_split(c,2))
print(np.array_split(c,3))
print(np.array_split(d,4))
print(np.array_split(d,5))
e = np.array_split(d,5)
print(e[2])

[array([10, 20, 30, 40, 50])]
[array([10, 20, 30]), array([40, 50])]
[array([10, 20]), array([30, 40]), array([50])]
[array([60, 70]), array([80]), array([90]), array([100])]
[array([60]), array([70]), array([80]), array([90]), array([100])]
[80]


In [146]:
conc = np.concatenate([dim2arr1,dim2arr2],axis=0)
print(conc,"\n")
print(np.array_split(conc,1),"\n")
print(np.array_split(conc,2),"\n")
print(np.array_split(conc,3),"\n")
print(np.array_split(conc,4),"\n")
print(np.array_split(conc,5),"\n")

[[32 54]
 [20 40]
 [94 73]
 [53 16]] 

[array([[32, 54],
       [20, 40],
       [94, 73],
       [53, 16]])] 

[array([[32, 54],
       [20, 40]]), array([[94, 73],
       [53, 16]])] 

[array([[32, 54],
       [20, 40]]), array([[94, 73]]), array([[53, 16]])] 

[array([[32, 54]]), array([[20, 40]]), array([[94, 73]]), array([[53, 16]])] 

[array([[32, 54]]), array([[20, 40]]), array([[94, 73]]), array([[53, 16]]), array([], shape=(0, 2), dtype=int32)] 



ADDING / REMOVING ARRAY ELEMENTS

In [164]:
#Append item at last index . Higher dim array will be converted to 1D and then value is appended
# np.append ( array_name, value)
evens = np.array([20,40,60,80])
print(np.append(evens, 100))
print()
odds = np.array([[10,30],[50,70]])
print(np.append(odds,90))
print()
print(np.append(odds,[110,130],))
odds

[ 20  40  60  80 100]

[10 30 50 70 90]



NameError: name 'true' is not defined

In [161]:
# Insert items to array
# np.insert( array_name, position, value)
mid_odd = np.array([20,40,60,80])
print(np.insert(mid_odd, 2, 50 ))
print()
mid_set = np.array([[10,30, 60,80]])
print(np.insert(mid_set,2,[40,50]))
print()
mid_seq = np.array([[10,20],[50,60]])
print(np.insert(mid_seq,1,[30,40],axis=1))
print()
print(np.insert(mid_seq,1,[30,40],axis=0))
print()
print(np.insert(mid_seq,[1,2],[35],axis=1))
print()
print(np.insert(mid_seq,[1,2],[35],axis=0))

[20 40 50 60 80]

[10 30 40 50 60 80]

[[10 30 20]
 [50 40 60]]

[[10 20]
 [30 40]
 [50 60]]

[[10 35 20 35]
 [50 35 60 35]]

[[10 20]
 [35 35]
 [50 60]
 [35 35]]


In [170]:
# Deleting array element. if delete mentioned without axis, Higher dim array will be converted to 1D and then value at location is deleted
# np.delete( array_name, [element])
dim1 = np.array([10,20,30,40,50,60,70,80,90])
print(dim1)
print(np.delete(dim1 , 5))
print()
dim2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(dim2)
print()
print(np.delete(dim2 , 1))
print()
print(np.delete(dim2 , 1, axis = 0))
print()
print(np.delete(dim2 , 1, axis = 1))

[10 20 30 40 50 60 70 80 90]
[10 20 30 40 50 70 80 90]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 3 4 5 6 7 8 9]

[[1 2 3]
 [7 8 9]]

[[1 3]
 [4 6]
 [7 9]]


SORT , FILTER , SEARCH array elements

In [175]:
unarr = np.array([7,10,4,9,2,5,8,1,3,6])
print("Unarranged 1D array - ",unarr)
arrng = np.sort(unarr)
print("Arranged 1D array - ",arrng)
print()
unarr2d = np.array([[80,60,40,20,00],[90,70,50,30,10]])
print("Unarranged 2D array - \n",unarr2d)
arrng2d = np.sort(unarr2d)
print("Arranged 2D array\n",arrng2d)

Unarranged 1D array -  [ 7 10  4  9  2  5  8  1  3  6]
Arranged 1D array -  [ 1  2  3  4  5  6  7  8  9 10]

Unarranged 2D array - 
 [[80 60 40 20  0]
 [90 70 50 30 10]]
Arranged 2D array
 [[ 0 20 40 60 80]
 [10 30 50 70 90]]


In [176]:
# Search with condition
arry = np.array([54,23,76,61,35,84])
ser = np.where(arry % 2 == 0)
print(ser)


(array([0, 2, 5], dtype=int64),)


In [186]:
#SearchSorted with condition. requires array list to be sorted
ary = np.array([54,23,76,61,35,84])
srtary = np.sort(ary)
ss = np.searchsorted(srtary, 84)
print("The searched value is present at position ",ss," in the sorted array")

The searched value is present at position  5  in the sorted array


In [188]:
# Filter based on condition. only true values are kept in output
val = np.array([20,30,40,50])
print("Original values ",val)
cond = [True, False, True, False]
filtrd = val[cond]               # can be any condition like val>35, etc
print("After filtering ",filtrd)

Original values  [20 30 40 50]
After filtering  [20 40]


AGGREGATE FUNCTIONS ON ARRAY

In [189]:
a = np.array([20,40,60,70])
print(a)
print("Sum of array values is ",np.sum(a))
print("Min of array values is ",np.min(a))
print("Max of array values is ",np.max(a))
print("Size of array values is ",np.size(a))
print("Mean of array values is ",np.mean(a))
print("Cumulative sum of array values is ",np.cumsum(a))
print("Cumultive product of array values is ",np.cumprod(a))

[20 40 60 70]
Sum of array values is  190
Min of array values is  20
Max of array values is  70
Size of array values is  4
Mean of array values is  47.5
Cumulative sum of array values is  [ 20  60 120 190]
Cumultive product of array values is  [     20     800   48000 3360000]


In [196]:
# e.g. WAP to find total sales of all products in shop (total_sales=sum of quantity*rate)
price = np.array([100,150,199,200,250,130])
quantity = np.array([10,50,30,40,30,10])
print("Prices - ",price,"\nQuantity - ",quantity)
#print("\n")
total = np.cumprod([price,quantity], axis = 0)
print("Total Sales = ",total[1].sum())

Prices -  [100 150 199 200 250 130] 
Quantity -  [10 50 30 40 30 10]
Total Sales =  31270


STATISTICAL FUNCTIONS on Arrays

In [198]:
import statistics as stats
values = [200,150,150,130,200,200,170,188]
a = np.array([values])
print(np.mean(values))
print(np.median(values))
print(stats.mode(values))
print(np.std(values))
print(np.var(values))

173.5
179.0
200
25.802131694881336
665.75


In [201]:
# correlation coefficient
# -1 represents inversly proportional
# +1 represents positively related
#  0 represents no relation

#wap to find relation between tobaco conumption and death
tobaco_consumptn = [30,50,10,30,50,40]
deaths = [100, 120, 70, 100, 120, 112]
print(np.corrcoef([tobaco_consumptn,deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [202]:
#wap to find relation between price and sales
price = [300,100,350,150,200]
sales = [10,20,7,17,3]
print(np.corrcoef([price,sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
